version: 2.1

executors:
  ubuntu-build:
    description: "A regular build executor based on ubuntu image"
    docker:
      # NOTE: Update this from https://github.com/envoyproxy/envoy-build-tools/blob/master/toolchains/rbe_toolchains_config.bzl#L8
      - image: envoyproxy/envoy-build-ubuntu:736b8db2e1f0b55edb50719d2f8ddf383f46030b
    resource_class: xlarge
    working_directory: /source

jobs:
   envoy_fips:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - setup_remote_docker
       - checkout
       - run: ci/do_circle_ci.sh bazel.fips
       - add_ssh_keys:
           fingerprints:
             - "SHA256:1MNg4FGsDjkx9qGESJuSRqm4kvwYITfq/KIDK/z0X5A"
       - run: ci/api_mirror.sh
       - store_artifacts:
           path: /build/envoy/generated
           destination: /

workflows:
  version: 2
  all:
    jobs:
      - envoy_fips
